export const gameProducts = [
    {
    id: 1001,
    title: "Ping Pong",
    price: 399,
    platform: "PC",
    image: "images/GameHub_covers.jpg",
},
{
    id: 1002,
    title: "Forge Legend",
    price: 499,
    platform: "Playbox",
    images: "images/GameHub_covers10.jpg",
},
{
    id: 1003,
    title: "Assassin",
    price: 299,
    platform: "PS",
    images: "images/GameHub_covers5.jpg",
},
{
    id: 1004,
    title: "Black",
    price: 599,
    platform: "PC",
    images: "images/GameHub_covers3.jpg",
},
{
    id: 1005,
    title: "Cyberpunk",
    price: 399,
    platform: "Playbox",
    images: "images/GameHub_covers9.jpg",
},
{
    id: 1006,
    title: "Boxer",
    price: 199,
    platform: "PS",
    images: "images/GameHub_covers8.jpg",
},
{
    id: 1007,
    title: "Furious",
    price: 499,
    platform: "Playbox",
    images: "images/GameHub_covers4.jpg",
},
{
    id: 1008,
    title: "Racing",
    price: 699,
    platform: "PC",
    images: "images/GameHub_covers7.jpg",
},
{
    id: 1009,
    title: "Super Duper",
    price: 299,
    platform: "Playbox",
    images: "images/GameHub_covers2.jpg",
},
{
    id: 10010,
    title: "Space War",
    price: 799,
    platform: "PS",
    images: "images/GameHub_covers6.jpg",
},
];