export const gameProductsArray = [
  {
    id: 1001,
    title: "Ping Pong",
    price: 399,
    seller: "Peter",
    platform: "Platform (PC)",
    image: "images/GameHub_covers.jpg",
  },
  {
    id: 1002,
    title: "Forge Legend",
    price: 499,
    seller: "Jack",
    platform: "Platform (Playbox)",
    image: "images/GameHub_covers10.jpg",
  },
  {
    id: 1003,
    title: "Assassin",
    price: 299,
    seller: "Gary",
    platform: "Platform (PS)",
    image: "images/GameHub_covers5.jpg",
  },
  {
    id: 1004,
    title: "Black",
    price: 599,
    seller: "Bobby",
    platform: "Platform (PS)",
    image: "images/GameHub_covers3.jpg",
  },
  {
    id: 1005,
    title: "Cyberpunk",
    price: 399,
    seller: "David",
    platform: "Platform (Playbox)",
    image: "images/GameHub_covers9.jpg",
  },
  {
    id: 1006,
    title: "Boxer",
    price: 199,
    seller: "Brock",
    platform: "Platform (PC)",
    image: "images/GameHub_covers8.jpg",
  },
  {
    id: 1007,
    title: "Furious",
    price: 499,
    seller: "Johnny",
    platform: "Platform (PS)",
    image: "images/GameHub_covers4.jpg",
  },
  {
    id: 1008,
    title: "Racing",
    price: 699,
    seller: "Nelly",
    platform: "Platform (Playbox)",
    image: "images/GameHub_covers7.jpg",
  },
  {
    id: 1009,
    title: "Super Duper",
    price: 299,
    seller: "Sam",
    platform: "Platform (PS)",
    image: "images/GameHub_covers2.jpg",
  },
  {
    id: 10010,
    title: "Space War",
    price: 799,
    seller: "Crystal",
    platform: "Platform (PC)",
    image: "images/GameHub_covers6.jpg",
  },
];
